defaults:

  - common_environment
  - _self_

# Environment Name
env_name:           ['custom','UnSafeEnv']

# Safety Parameters
safety_threshold:   1.0

# Test and Violation Environments
violation_env_epochs:   50
test_episode_number:    10
