defaults:

  - common_environment
  - _self_

# Environment Name
env_name:           ['custom','UnSafeEnv']

# Safety Parameters
safety_threshold:   1.0

# Test and Violation Environments
test_environment:       true
violation_environment:  true
test_env_epochs:        1
violation_env_epochs:   50
test_episode_frequency: 250
